openingo:
  redis:
    enable: true
  http:
    request:
      cors:
        allowed-header: "*"
        enable: true
        allowed-all: true
      log:
        enable: true
      error:
        enable: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dbadmin
    url: jdbc:mysql://127.0.0.1/test?useSSL=false&serverTimezone=GMT%2B8