openingo:
  redis:
    enable: true
  http:
    request-error:
      enable: true
    request-log:
      enable: true
    cors:
      enable: true
      allowed-all: true
      allowed-header: "*"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dbadmin
    url: jdbc:mysql://127.0.0.1/test?useSSL=false&serverTimezone=GMT%2B8