openingo:
  redis:
    enable: true
  http:
    request:
      error:
        enable: true
      log:
        enable: true
      cors:
        enable: true
        allowed-all: true
        allowed-header: "*" # when allowed-all is true will ignore